<script type="text/javascript" src="{{ \Illuminate\Support\Facades\URL::asset('/source/spay/grid.js') }}"></script>
<script type="text/javascript" src="{{ \Illuminate\Support\Facades\URL::asset('/source/spay/version.js') }}"></script>
<script type="text/javascript" src="{{ \Illuminate\Support\Facades\URL::asset('/source/spay/detector.js') }}"></script>
<script type="text/javascript" src="{{ \Illuminate\Support\Facades\URL::asset('/source/spay/formatinf.js') }}"></script>
<script type="text/javascript" src="{{ \Illuminate\Support\Facades\URL::asset('/source/spay/errorlevel.js') }}"></script>
<script type="text/javascript" src="{{ \Illuminate\Support\Facades\URL::asset('/source/spay/bitmat.js') }}"></script>
<script type="text/javascript" src="{{ \Illuminate\Support\Facades\URL::asset('/source/spay/datablock.js') }}"></script>
<script type="text/javascript" src="{{ \Illuminate\Support\Facades\URL::asset('/source/spay/bmparser.js') }}"></script>
<script type="text/javascript" src="{{ \Illuminate\Support\Facades\URL::asset('/source/spay/datamask.js') }}"></script>
<script type="text/javascript" src="{{ \Illuminate\Support\Facades\URL::asset('/source/spay/rsdecoder.js') }}"></script>
<script type="text/javascript" src="{{ \Illuminate\Support\Facades\URL::asset('/source/spay/gf256poly.js') }}"></script>
<script type="text/javascript" src="{{ \Illuminate\Support\Facades\URL::asset('/source/spay/gf256.js') }}"></script>
<script type="text/javascript" src="{{ \Illuminate\Support\Facades\URL::asset('/source/spay/decoder.js') }}"></script>
<script type="text/javascript" src="{{ \Illuminate\Support\Facades\URL::asset('/source/spay/qrcode.js') }}"></script>
<script type="text/javascript" src="{{ \Illuminate\Support\Facades\URL::asset('/source/spay/findpat.js') }}"></script>
<script type="text/javascript" src="{{ \Illuminate\Support\Facades\URL::asset('/source/spay/alignpat.js') }}"></script>
<script type="text/javascript" src="{{ \Illuminate\Support\Facades\URL::asset('/source/spay/databr.js') }}"></script>
<script type="text/javascript" src="{{ \Illuminate\Support\Facades\URL::asset('/source/spay/qiniu.min.js') }}"></script>
<script type="text/javascript"  src="{{ \Illuminate\Support\Facades\URL::asset('/source/spay/zepto.min.js') }}"></script>
<script type="text/javascript"  src="{{ \Illuminate\Support\Facades\URL::asset('/source/spay/hprose.min.js') }}"></script>
<script type="text/javascript"  src="{{ \Illuminate\Support\Facades\URL::asset('/source/spay/md5.min.js') }}"></script>