<?php
return [
    'group1'=>[
        'name'=>'基础版套餐',
        'price'=>'29.99',
        'rate'=>0.3,
        'type'=>[
            "type_1"=>[
                'rate'=>1
            ],
            "type_6"=>[
                'rate'=>0.88
            ],
            "type_12"=>[
                'rate'=>0.83
            ],
            "type_24"=>[
                'rate'=>0.7
            ],
            "type_36"=>[
                'rate'=>5
            ]
        ]
    ],
    'group2'=>[
        'name'=>'高级版套餐',
        'price'=>'59.99',
        'rate'=>0.2,
        'type'=>[
            "type_1"=>[
                'rate'=>1
            ],
            "type_6"=>[
                'rate'=>0.88
            ],
            "type_12"=>[
                'rate'=>0.83
            ],
            "type_24"=>[
                'rate'=>0.7
            ],
            "type_36"=>[
                'rate'=>5
            ]
        ]
    ],
    'group3'=>[
        'name'=>'专业版套餐',
        'price'=>'99.99',
        'rate'=>0.1,
        'type'=>[
            "type_1"=>[
                'rate'=>1
            ],
            "type_6"=>[
                'rate'=>0.88
            ],
            "type_12"=>[
                'rate'=>0.83
            ],
            "type_24"=>[
                'rate'=>0.7
            ],
            "type_36"=>[
                'rate'=>5
            ]
        ]
    ],
];
